- hosts: appservers
  remote_user: admin
  become: true
  vars:
    nginx_port: 80
    root_dir: /etc/nginx

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy HTML file
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
      notify: Restart Nginx

    - name: Copy Nginx configuration
      copy:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
